---
name: Class-Std-Fast
version: 0.0.4
author:
  - "Andreas 'ac0v' Specht - ACID@cpan.org"
abstract: faster but less secure than Class::Std
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Std: 0.0.8
  Data::Dumper: 0
  Scalar::Util: 0
  version: 0
build_requires:
  Test::More: 0
provides:
  Class::Std::Fast:
    file: lib/Class/Std/Fast.pm
    version: 0.0.4
  Class::Std::Fast::Storable:
    file: lib/Class/Std/Fast/Storable.pm
    version: 0.0.4
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
